feat(new-sample):Github PR Dashboard
canonic-dev/canonic-samples pull request #22
Opened 2021-11-17 15:38 UTC by ajayjarhad

2021-11-20 08:30 UTC, pagrawl3 requested changes

2021-11-20 08:30 UTC, pagrawl3 commented on github-pr-dashboard/src/components/Container/Container.js
> +      const pullRequests = prData.pullRequests.map((item) => item.github);
these should all be outside the useEffect and used directly without storing them in state.

```js
const pullRequests = React.useMemo(() => prData?.pullRequests?.map(item => item.github)?.[0] || [], [prData?.pullRequests])

const opened = React.useMemo(() => pullRequests[0].filter((item) => item.state === "open"), [pullRequests])
...
```

2021-11-22 06:45 UTC, iamsimranjot commented
@ajayjarhad Can we also change the name of the App that comes to the header? It shows `React App`, can change it to `PR Dashboard`. @pagrawl3 We can also add Canonic's Logo as a favicon for all our sample repositories?

2021-11-25 05:37 UTC, pagrawl3 approved these changes

2021-11-25 05:58 UTC, merged